[build]
  publish = "out/"

[build.environment]
  # Use only for build cache.
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://gnosis-safe.io"

[[redirects]]
  from = "/streams/*"
  to = "/streams/[_v1Network]/[_tx]/[_log]/[[..._rest]].html"
  status = 200
  force = false

[[redirects]]
  from = "/stream/*"
  to = "/stream/[_network]/[_stream].html"
  status = 200
  force = false

[[redirects]]
  from = "/token/*"
  to = "/token/[_network]/[_token].html"
  status = 200
  force = false

[[redirects]]
  from = "/dashboard"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/currencies"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/transactions"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/distribution"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/activities"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/settings"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/GT-Walsheim-Pro-Medium.otf"
  to = "/fonts/GT-Walsheim-Pro-Medium.otf"
  status = 301
  force = false

[[redirects]]
  from = "/GT-Walsheim-Pro-Regular.otf"
  to = "/fonts/GT-Walsheim-Pro-Regular.otf"
  status = 301
  force = false

[[redirects]]
  from = "/static/*"
  to = "https://v1.superfluid.finance/static/:splat"
  status = 301
  force = false