name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:

  test-suites:
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome , firefox ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        if: ${{ matrix.browser == 'firefox' }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          headless: true
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          record: true
          env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
