name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  test-suites:
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v2

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        if: ${{ matrix.browser == 'firefox' }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: c-hive/gha-yarn-cache@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Install JS dependencies
        run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0 # Check the source code before updating version because it uses personal Netlify access token which does not have granular access control.
        id: waitForDeployment
        with:
          site_id: "aa82cf1e-ce5d-432f-99bf-77a0b8c13277"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: ${{ matrix.browser }}
          wait-on: ${{ steps.waitForDeployment.outputs.url }}
          wait-on-timeout: 180
          record: true
          env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl: ${{ steps.waitForDeployment.outputs.url }}
