name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  test_setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      netlify_url: ${{ steps.waitForDeployment.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0 # Check the source code before updating version because it uses personal Netlify access token which does not have granular access control.
        id: waitForDeployment
        with:
          site_id: "aa82cf1e-ce5d-432f-99bf-77a0b8c13277"
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  test-suites:
    timeout-minutes: 30
    needs: ["test_setup"]
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1,2,3,4,5,6,7,8]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          parallel: true
          record: true
          env: STATIC_BALANCE_ACCOUNT_PRIVATE_KEY=${{ secrets.STATIC_BALANCE_ACCOUNT_PRIVATE_KEY }},ONGOING_STREAM_ACCOUNT_PRIVATE_KEY=${{ secrets.ONGOING_STREAM_ACCOUNT_PRIVATE_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.V2_CYPRESS_RECORD_KEY }}
          CYPRESS_baseUrl: ${{ needs.test_setup.outputs.netlify_url }}